apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
  labels:
    app: my-python-app
spec:
  type: {{ .Values.service.type }}
  ports:
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80

  selector:
    app: my-python-app

