apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mnist-classifier
  template:
    metadata:
      labels:
        app: mnist-classifier
    spec:
      containers:
      - name: mnist-classifier
        image: user/my_ml_app:latest
        ports:
        - containerPort: 80
