replicaCount: 2

image:
  repository: chaanani/mycv
  tag: 3.9
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8501
  targetPort: 8501

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
