name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
      - develop
      - feature-*
  pull_request:
    branches: 
      - main
      - develop
      - feature-*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'ci.yml')
    strategy :
      matrix:
        python-version : ['3.6', '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - run: echo "ci.yml a été modifié."
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      if: github.ref=='refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: chaanani/mycv:latest

  
        
